name: Deploy to Unraid

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Unraid server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.UNRAID_HOST }}
        username: ${{ secrets.UNRAID_USER }}
        key: ${{ secrets.UNRAID_SSH_KEY }}
        port: 2222
        script: |
          cd /mnt/user/appdata/helloworld
          git pull origin master
          docker restart test123
